INSERT INTO colors (`id`,`color`,`code`) VALUES (1,'Rojo Pasión','#FF7070');
INSERT INTO colors (`id`,`color`,`code`) VALUES (2,'Naranja Marte','#FFB870');
INSERT INTO colors (`id`,`color`,`code`) VALUES (3,'Amarillo Merengue','#FFFF70');
INSERT INTO colors (`id`,`color`,`code`) VALUES (4,'Verde Monasterio','#B8FF70');
INSERT INTO colors (`id`,`color`,`code`) VALUES (5,'Verde Lima','#70FF70');
INSERT INTO colors (`id`,`color`,`code`) VALUES (6,'Verde Menta','#70FFB8');
INSERT INTO colors (`id`,`color`,`code`) VALUES (7,'Cyan Aguamarina','#70FFFF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (8,'Azul Larimar','#70B7FF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (9,'Azul Majorelle','#7070FF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (10,'Morado Lavanda','#B870FF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (11,'Rosa Orquidea','#FF70FF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (12,'Rosa Flamenco','#FF70B8');
INSERT INTO colors (`id`,`color`,`code`) VALUES (13,'Rojo Intenso','#ff0000');
INSERT INTO colors (`id`,`color`,`code`) VALUES (14,'Naranja Tigre','#ff8000');
INSERT INTO colors (`id`,`color`,`code`) VALUES (15,'Amarillo Canario','#ffff00');
INSERT INTO colors (`id`,`color`,`code`) VALUES (16,'Verde Peridoto','#80ff00');
INSERT INTO colors (`id`,`color`,`code`) VALUES (17,'Verde Digital','#00ff00');
INSERT INTO colors (`id`,`color`,`code`) VALUES (18,'Verde Crisoprasa','#00ff80');
INSERT INTO colors (`id`,`color`,`code`) VALUES (19,'Cyan Apatito','#00FFFF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (20,'Azul Munsell','#007FFF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (21,'Azul Imperial','#0000FF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (22,'Morado Uva','#8000FF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (23,'Rosa Chicle','#FF00FF');
INSERT INTO colors (`id`,`color`,`code`) VALUES (24,'Rosa Magenta','#FF0080');
INSERT INTO colors (`id`,`color`,`code`) VALUES (25,'Rojo Vino','#800000');
INSERT INTO colors (`id`,`color`,`code`) VALUES (26,'Naranja Jengibre','#804000');
INSERT INTO colors (`id`,`color`,`code`) VALUES (27,'Amarillo Oliva','#808000');
INSERT INTO colors (`id`,`color`,`code`) VALUES (28,'Verde Jungla','#408000');
INSERT INTO colors (`id`,`color`,`code`) VALUES (29,'Verde Trebol','#008000');
INSERT INTO colors (`id`,`color`,`code`) VALUES (30,'Verde Malaquita','#008040');
INSERT INTO colors (`id`,`color`,`code`) VALUES (31,'Azul Bondi','#008080');
INSERT INTO colors (`id`,`color`,`code`) VALUES (32,'Azul Cobalto','#004080');
INSERT INTO colors (`id`,`color`,`code`) VALUES (33,'Azul Marino','#000080');
INSERT INTO colors (`id`,`color`,`code`) VALUES (34,'Morado Medianoche','#400080');
INSERT INTO colors (`id`,`color`,`code`) VALUES (35,'Morado Mora','#800080');
INSERT INTO colors (`id`,`color`,`code`) VALUES (36,'Morado Mermelada','#800040');
INSERT INTO colors (`id`,`color`,`code`) VALUES (37,'Blanco Puro','#ffffff');
INSERT INTO colors (`id`,`color`,`code`) VALUES (38,'Gris Delfin','#808080');
INSERT INTO colors (`id`,`color`,`code`) VALUES (39,'Negro Absoluto','#000000');
INSERT INTO colors (`id`,`color`,`code`) VALUES (40,'Traslúcido','#ffffff50');

INSERT INTO categories (`id`,`category`) VALUES (1,'Hogar');
INSERT INTO categories (`id`,`category`) VALUES (2,'Audio');
INSERT INTO categories (`id`,`category`) VALUES (3,'Entretenimiento');
INSERT INTO categories (`id`,`category`) VALUES (4,'SmartPhone');
INSERT INTO categories (`id`,`category`) VALUES (5,'Deporte');
INSERT INTO categories (`id`,`category`) VALUES (6,'Salud');
INSERT INTO categories (`id`,`category`) VALUES (7,'PC');
INSERT INTO categories (`id`,`category`) VALUES (8,'Construcción');
INSERT INTO categories (`id`,`category`) VALUES (9,'Electricidad');
INSERT INTO categories (`id`,`category`) VALUES (10,'Equipamiento');
